# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Nina-no-Burogu
tagline:             ''
description:         ''
url:                 https://matikin9.github.io/nina-no-burogu/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Nina Kin
  url:               http://ninakin.com
  email:             nina@ninakin.com

# Custom vars
version:             1.0.0
